### PR TITLE
logout on componentdidmount

### PR DESCRIPTION
**Pull request by tfolbrecht**
# Description

Trigger a logout on Landing Page to prevent inconsistent auth behavior. 
Runs logout on comonentdidmount for Landing Page

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change status
- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Manually tested on localhost, by authenticating, and verifying function did run on Landing Page

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by tfolbrecht** [comment]
[Make sure auth behavior is consistent](https://trello.com/c/43lbsIKn/126-make-sure-auth-behavior-is-consistent)

**Comment by tfolbrecht** [comment]
[Make sure auth behavior is consistent](https://trello.com/c/43lbsIKn/126-make-sure-auth-behavior-is-consistent)

**Review by dsnair — CHANGES_REQUESTED** [review]
Can you please update line 35 to `import {logout} from 'Auth/AuthPasswordless'`? `Auth/Auth` is not compatible with our auth0. It is dead code. I suggest we even remove it along with `components/Misc/Callback/Callback`. @tfolbrecht @GannonDetroit

**Comment by tfolbrecht** [comment]
> Can you please update line 35 to `import {logout} from 'Auth/AuthPasswordless'`? `Auth/Auth` is not compatible with our auth0. It is dead code. I suggest we even remove it along with `components/Misc/Callback/Callback`. @tfolbrecht @GannonDetroit

I'll do it, but if doesn't work as defined I'll repull this one

**Comment by tfolbrecht** [comment]
Clears all but cookies which are unused.

**Review by dsnair — APPROVED** [review]
Good job! Thank you 🔥

**Pull request merged**
