### PR TITLE
Training series pulling data from backend

### PR DESCRIPTION
**Pull request by JoeBugajski**
-image is generated randomly, to be replaced by image link in backend

# Description

Training series makes an axios call to the backend on mount. It comes back with an array of all training series, and renders them out. It also generates a random image for each training series, which will be replaced by new data in the backend eventually.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Change status
- [ ] Complete, tested, ready to review and merge

# How Has This Been Tested?

I've gone through the log in quite a few times, and the changes I've made seem stable thus far. 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by tfolbrecht — APPROVED** [review]
Progress! I like how you did this.
Looking good.

**Review by dsnair — CHANGES_REQUESTED** [review]
Since all the data is already in the redux store, you don't need to call `componentDidMount`. Use `mapStateToProps` to read data from the store and use `this.props` to render that data. I will show you what I am saying in a separate dev branch soon.

**Comment by JoeBugajski** [comment]
[Replace training series dummy data with data from backend](https://trello.com/c/J2m82dtR/111-replace-training-series-dummy-data-with-data-from-backend)

**Review by dsnair — APPROVED** [review]
Approved. Let's keep building. I will send you a dev branch for reference on Redux still.

**Pull request merged**
